Grocery Store (python, django - course project)/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

Grocery Store (python, django - course project)/grocery_store_project/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from app_grocery_shoping import views as gr_shoping
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', gr_shoping.index, name='index'),
    path('cart/', gr_shoping.cart, name='cart'),
    path('products/<slug:category>', gr_shoping.products, name='products'),
    path('product/<int:id>', gr_shoping.product, name='product'),
    path('address/', gr_shoping.add_model_address, name='add_address_new'),
    path('thank_you/', gr_shoping.thank_you, name='thank_you'),
    path('del/', gr_shoping.del_address, name='del'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [path('accaunts/', include('django.contrib.auth.urls'))]

Grocery Store (python, django - course project)/app_grocery_shoping/models.py
from pickle import FALSE
from django.db import models


class User(models.Model):

    name = models.CharField(blank=False, max_length=100)
    email = models.EmailField(blank=False, primary_key=True)
    image = models.ImageField(upload_to='uploads')
    day_of_birth = models.DateField(null=True)


class Delivery(models.Model):

    METHODS = [('p', 'Pick up in the pick-up point'),
               ('d', 'Deliver to my appartment')]

    country = models.CharField(blank=False, max_length=100)
    city = models.CharField(blank=False, max_length=100)
    address = models.CharField(blank=False, max_length=200)
    phone = models.CharField(blank=False, max_length=100)
    comment = models.TextField(max_length=300)
    method = models.CharField(choices=METHODS, max_length=1, blank=False)

    user = models.ForeignKey('User', on_delete=models.CASCADE)

CATEGORY = [('Fruits', 'Fruits'), ('Vegetables', 'Vegitables'), ('Milk-and-meat', 'Milk and Meat')]

class Cart(models.Model):

    product = models.CharField(blank=False, max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False)

    user = models.ForeignKey('User', on_delete=models.CASCADE)

class Product(models.Model):

    name = models.CharField(blank=False, max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    company = models.CharField(blank=False, max_length=100)
    image = models.ImageField(upload_to='uploads')

    category = models.CharField(choices=CATEGORY, max_length=20, blank=False)

Grocery Store (python, django - course project)/cart/models.py
from django.db import models

# Create your models here.

Grocery Store (python, django - course project)/app_grocery_shoping/forms.py
from django import forms
from .models import Delivery

class AddAddressViaModelForm(forms.ModelForm):

    class Meta():

        model = Delivery
        fields = ('country', 'city', 'address', 'phone', 'comment', 'method')

Grocery Store (python, django - course project)/cart/forms.py
from django import forms

PRODUCT_QUANTITY_SHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_SHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Grocery Store (python, django - course project)/app_grocery_shoping/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product, Delivery, User
from .forms import AddAddressViaModelForm
from cart.forms import CartAddProductForm

def index(request):
    return render(request, 'index.html')

def adress(request):
    return render(request, 'adress.html')

def cart(request):
    return render(request, 'cart.html')

def products(request, category):
    try:
        all_the_products = Product.objects.filter(category=category).order_by('-id')
        one_prod = all_the_products[0]
        return render(request, 'products.html', {'all_prod':all_the_products, 'one_pr':one_prod})
    except:
        return render(request, 'products.html')


def product(request, id):
    # try:
    prod = Product.objects.get(id=id)
    one_prod = Product.objects.get(id=id)
    cart_product_form = CartAddProductForm
    return render(request, 'product.html', {'prodid':prod, 'one_pr':one_prod, 'cart_product_form': cart_product_form})
    # except:
    #     response = "There is no product with such an id."
    #     return HttpResponse(response)


def add_model_address(request):

    address = AddAddressViaModelForm
    
    if request.method == 'POST':
        address = AddAddressViaModelForm(request.POST, request.FILES)

        if address.is_valid():
            new_address = address.save(commit=False)
            new_address.user = User.objects.get(email=request.user.email)

            new_address.save()
            address.save_m2m()
    
            return redirect('thank_you')
            
    a = {'address_new':address}

    try:
        ad_ad = Delivery.objects.filter(user=request.user.email)[0]
        a['ad_ad'] = ad_ad
    except:
        None

    return render(request, 'address.html', a)

def thank_you(request):
    return render(request, 'thank_you.html')

def pre_login(request):
    return render(request, 'pre_login.html')

def del_address(request):
    try:
        del_ad = Delivery.objects.filter(user=request.user.email)[0]
        del_ad.delete()
        return redirect('add_address_new')
    except:
        None

Grocery Store (python, django - course project)/cart/views.py
import imp
from tracemalloc import get_object_traceback
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from app_grocery_shoping.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    count = 0
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        count += 1
    context = {
        'cart': cart,
        'count':count,
    }

    return render(request, 'cart/detail.html', context)

def cart_count(request):
    cart = Cart(request)
    count = 0
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        count += 1

    return count

Grocery Store (python, django - course project)/app_grocery_shoping/templates/address.html
{% extends 'basis.html' %}

{% block content %}
{% load static %} 
{% if user.is_authenticated %}
    {% if ad_ad %}
        <div class="wrap_address_cart">
            <img class="silhouette" src="{% static 'app_grocery_shoping/pic/silhouette.png' %}" alt="">
            <div class="deliv_pointed_wrap">
                <h1 class="deliv_pointed">You'r delivery address:</h1>
                {% csrf_token %}
                <div class="descr_deliver_wrap">
                    <div><p>Country:</p>{{ ad_ad.country }} </div>
                    <div><p>City:</p>{{ ad_ad.city }}</div>
                    <div><p>Address:</p>{{ ad_ad.address }}</div>
                    <div><p>Phone:</p>{{ ad_ad.phone }}</div>
                    <div><p>Comment:</p>{{ ad_ad.comment }}</div>
                    <!-- <div><p>Deliver method:</p>{{ ad_ad.method }}</div>           -->
                </div>
                <h1 class="deliv_pointed">Change it?</h1>
                <a class="change" href="{% url 'del' %}">Yes</a>
                
            </div>
        </div>
    {% else %}
        <div class="wrap_address_cart">
            <img class="silhouette" src="{% static 'app_grocery_shoping/pic/silhouette.png' %}" alt="">
            <div class="address_card">
                <h1 class="head_address">Point your delivery address</h1>
                <form class="enter_address" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ address_new.as_p }}
                    <button class="btn_add_address" type="submit">Add address</button>
                </form>
            </div>
        </div>
    {% endif %}
{% else %}
<div class="wrap_address_cart">
    <h1 class="caution">Please login to Grocery Store to have a posibility to point a delivery address</h1>
</div>
{% endif %}

{% endblock %}

{% block title %} Address page - Grocery Store {% endblock %}

Grocery Store (python, django - course project)/app_grocery_shoping/templates/basis.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'app_grocery_shoping/css/css_index.css' %}" type="text/css">
    <style>
        .text {
            font-size: 20pt;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="body">
        <div class="header_wraper">
            <div class="header">
                <div class="home_and_category">
                    <div class="img_home">
                        <a href="{% url 'index' %}" class="link_header"></a>
                    </div>
                    <div onclick="show_categories()" class="img_category">
                        <ul id="category_click" class="dropdown_content_category">
                            <li>
                                <a href="{% url 'products' 'Fruits' %}" class="link_categories">Fruits</a>
                            </li>
                            <li>
                                <a href="{% url 'products' 'Vegetables' %}" class="link_categories">Vegitables</a>
                            </li>
                            <li>
                                <a href="{% url 'products' 'Milk-and-meat' %}" class="link_categories">Milk and Meat</a>
                            </li>
                        </ul>
                    </div>
                    <h2 class="name_goods">{% block prods_name %}{% endblock %}</h2>
                </div>

                <div class="adress_and_cart">
                    
                        {% if user.is_authenticated %}
                            <a class="login" href="{% url 'logout' %}?next={{ request.path }}">                      
                                Logout
                            </a>
                        {% else %}
                            <a class="login" href="{% url 'login' %}?next={{ request.path }}">                      
                                Login
                            </a>
                            <div class="log_in">
                            
                            </div>
                        {% endif %}

                    <div class="img_adress">
                        <a href="{% url 'add_address_new' %}"></a>
                    </div>
                    <div class="img_cart">
                        <a href="{% url 'cart' %}" class="link_header"></a>
                        {% if cart|length > 0 %}

                        <div class="cart_length">
                        {{ counts }}
                        </div>     
                        
                        {% else %}
                        {% endif %}                 
                    </div>
                </div>
            </div>
        </div>

        <div class="main_part">
            {% block content %}
            {% endblock %}
        </div>
        <div class="footer">
            <div class="mader_name">Made by Denkevich Eugene on Django</div>
        </div>
    </div>

</body>

<script>

    function show_categories() {
        document.getElementById("category_click").classList.toggle("show_it")
    }
    window.onclick = function (event) {
        if (!event.target.matches('.img_category')) {
            var dropdowns = document.getElementsByClassName("dropdown_content_category");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show_it')) {
                    openDropdown.classList.remove('show_it');
                }
            }
        }
    }

</script>

</html>

Grocery Store (python, django - course project)/app_grocery_shoping/templates/cart/detail.html
{% extends 'basis.html' %}
{% load static %}

{% block title %} Cart - Grocery Store {% endblock %}

{% block content %}
<div class="cart_card_wrap">
    <div class="cart_card">
        <table class="cart_table">
            <thead>
                <tr class="tr_cart">
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Price/kg</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img class="img_cart_prod"
                                src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
                                alt="">
                        </a>
                    </td>
                    <td>{{ product.name|capfirst }}</td>
                    <td>
                        <form class="update" action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <a class="remove_item" href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
            </tbody>
        </table>
        <div class="odrer_total">
            <p>
                Total: ${{ cart.get_total_price }}
            </p>
            <p>
                <a href="#" class="button">Make an order</a>
            </p>
        </div>
    </div>

</div>

{% endblock %}

Grocery Store (python, django - course project)/app_grocery_shoping/templates/index.html
{% extends 'basis.html' %}

{% block content %}
<!-- {% load static %} -->
    <div class="description">
        <img src="{% static 'app_grocery_shoping/pic/delivery_main.png' %}" alt="delivery_main" class="img_delivery_main">
        <p><b>Welcome to Grocery Store!</b><br>We provides food delivery services and hope that you'll find the
            product you're looking for.</p>
    </div>
    <hr>
    <div class="description">
        <p>Click on the Categry button and choose the necessary category.</p>
        <img src="{% static 'app_grocery_shoping/pic/instruct_choice_category.png' %} " alt="instruction_category"
            class="img_instruction_category">
    </div>
    <hr>
    <div class="description">
        <img src="{% static 'app_grocery_shoping/pic/instruct_delivery.png' %}" alt="instruction_category"
            class="img_instruction_category">
        <p>Click on the "Point adress" button and enter the adress you need for a successfull delivering.</p>
    </div>
{% endblock %}

Grocery Store (python, django - course project)/app_grocery_shoping/templates/product.html
{% extends 'basis.html' %}

{% block content %}
{% load static %}
    <div class="goods" style="justify-content: center;">
        <div style="flex: none; justify-content: space-between; width: 600px;" class="refer_prod">
            {% if prodid.image %}
            <img style="padding: 5px 10px" src="{{ prodid.image.url }}" alt="">
            {% else %}
            <img src="{% static 'app_grocery_shoping/pic/goods/none.png' %}" alt="">
            {% endif %}
            <div style="padding: 0px 20px;">
                <div class="discr">
                    <div>
                        <h2>{{ prodid.price }} $ / kg</h2>
                        <p>{{ prodid.name|capfirst }}</p>
                    </div>
                </div>
                <h5>Company: {{ prodid.company }}</h5>
                <form class="add_to_cart" action="{% url 'cart:cart_add' prodid.id %}" method="post">
                    {{ cart_product_form}}
                    {% csrf_token %}
                    <input type="submit" value="Add to cart">
                </form>
            </div>
            <!-- <img src="{% static 'app_grocery_shoping/pic/goods/cart_prod_individual.png' %}" alt=""> -->


        </div>
        
    </div>
    
{% endblock %}}

{% block prods_name %}

    {{ one_pr.category }}

{% endblock %}

{% block title %} {{ prodid.name|capfirst }} - Grocery Store {% endblock %}

Grocery Store (python, django - course project)/app_grocery_shoping/templates/products.html
{% extends 'basis.html' %}

{% block content %}
    {% load static %}
    <div class="goods">
        {% for prod in all_prod %}
        <a href="{% url 'product' prod.id %}" class="refer_prod">
            {% if prod.image %}
            <img src="{{ prod.image.url }}" alt="">
            {% else %}
            <img src="{% static 'app_grocery_shoping/pic/goods/none.png' %}" alt="">
            {% endif %}
            <div>
                <div class="discr">
                    <div>
                        <h2>{{ prod.price|floatformat:2 }} $ / kg</h2>
                        <p>{{ prod.name|capfirst }}</p>
                    </div>
                    <!-- <img src="{% static 'app_grocery_shoping/pic/goods/cart_prod.png' %}" alt=""> -->
                </div>
                <h5>Company: {{ prod.company|capfirst }}</h5>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}

{% block prods_name %}

    {{ one_pr.category }}

{% endblock %}

{% block title %} {{ one_pr.category }} - Grocery Store {% endblock %}

Grocery Store (python, django - course project)/app_grocery_shoping/templates/thank_you.html
{% extends 'basis.html' %}

{% block content %}
{% load static %}
<div class="thank_you_wrapper">
    <h2 class="thank_you">Thank you! Now you can continue making an order.</h2>
    <img src="{% static 'app_grocery_shoping/pic/hook.png' %}" alt="">
</div>
{% endblock %}

{% block title %} Thank you! - Grocery Store {% endblock %}